"""Generated from spec/effect-transition-v1.json. DO NOT EDIT BY HAND."""
from __future__ import annotations

SPEC_SHA256 = "06b7d68f0104180e779a09c470d988f7b1f8a5d8ff595251d457f4acd9bb3f86"
EXECUTION_STATES = ('planned',
 'prepared',
 'authorized',
 'started',
 'unknown',
 'receipt_recorded',
 'reconciled',
 'execution_failed')
TERMINAL_STATES = frozenset(('receipt_recorded', 'reconciled', 'execution_failed'))
AMBIGUOUS_STATES = frozenset(('started', 'unknown'))
LEGAL_EDGES = frozenset((('authorized', 'started'),
 ('planned', 'prepared'),
 ('prepared', 'authorized'),
 ('started', 'execution_failed'),
 ('started', 'prepared'),
 ('started', 'receipt_recorded'),
 ('started', 'unknown'),
 ('unknown', 'execution_failed'),
 ('unknown', 'prepared'),
 ('unknown', 'receipt_recorded'),
 ('unknown', 'reconciled')))
COMMANDS = {'prepare': {'sources': ('planned',),
             'target': 'prepared',
             'requested_effects': (),
             'idempotent_sources': ()},
 'authorize': {'sources': ('prepared',),
               'target': 'authorized',
               'requested_effects': (),
               'idempotent_sources': ('authorized',)},
 'start': {'sources': ('authorized',),
           'target': 'started',
           'requested_effects': ('provider.execute',),
           'idempotent_sources': ()},
 'mark_unknown': {'sources': ('started',),
                  'target': 'unknown',
                  'requested_effects': ('provider.reconcile',),
                  'idempotent_sources': ()},
 'recover_orphan': {'sources': ('started',),
                    'target': 'unknown',
                    'requested_effects': ('provider.reconcile',),
                    'idempotent_sources': ()},
 'provider_retryable_pre_effect_failure': {'sources': ('started',),
                                           'target': 'prepared',
                                           'requested_effects': ('authorization.refresh_required',),
                                           'idempotent_sources': ()},
 'provider_definitive_failure': {'sources': ('started',),
                                 'target': 'execution_failed',
                                 'requested_effects': (),
                                 'idempotent_sources': ()},
 'record_receipt': {'sources': ('started', 'unknown'),
                    'target': 'receipt_recorded',
                    'requested_effects': (),
                    'idempotent_sources': ()},
 'reconcile_happened': {'sources': ('unknown',),
                        'target': 'reconciled',
                        'requested_effects': (),
                        'idempotent_sources': ()},
 'reconcile_not_happened_terminal': {'sources': ('unknown',),
                                     'target': 'execution_failed',
                                     'requested_effects': (),
                                     'idempotent_sources': ()},
 'reconcile_not_happened_retry': {'sources': ('unknown',),
                                  'target': 'prepared',
                                  'requested_effects': ('authorization.refresh_required',),
                                  'idempotent_sources': ()}}
